"""update orders

Revision ID: c7a2036c3b1d
Revises: 9a1b4361da0d
Create Date: 2024-02-07 16:33:11.537689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a2036c3b1d'
down_revision: Union[str, None] = '9a1b4361da0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), server_default='new', nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
